# import numpy as np
# numbers = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# # print(numbers)
# # print(numbers*2)
# # print(numbers.shape)
# # print(numbers.ndim)
# # print(numbers.size)
# # print(numbers[:,1])
# # print(numbers[2,2])
# # print(numbers[1])
# # print(numbers[1:4])
# # print(numbers[1:3,1:3])
# # print(numbers[:,1:3])
# # print(numbers[1:4,:])
# # print(numbers + 10)
# # print(numbers - 5)
# # print(numbers * 3)
# # print(np.sum(numbers))
# # print(numbers.sum())
# # print(numbers.mean())
# # print(numbers.min())
# # print(numbers.max())
# # print(np.zeros((10,10)))
# # print(np.ones(5))
# # print(np.arange(10,20,2))
import numpy as np
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))
array = []
for row in range(rows):
    row = list(map(int, input(f"Enter row {row+1}: ").split()))
    array.append(row)
numbers = np.array(array)
print(numbers.shape)
print(numbers[:,2])
print(numbers.mean())
print(numbers*2)
print(numbers[rows//2,cols//2])
