import numpy as np
A = np.random.randint(1,20,size = 5)
print(A)
B = np.random.rand(5)
print(B)
C = np.random.rand(5,5)
print(C)
D = np.random.uniform(low=10,high=20,size = 5)
print(D)
np.random.seed(10)
print(np.random.randint(1,20,size = 5))